POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VS code rest client is a pretty handy tool", 
    "important": true,
    "userId": "67d3f9b01f3483f71524b219"
}

###
GET http://localhost:3001/api/notes